# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import coco_planet_grpc_server_pb2 as coco__planet__grpc__server__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


class CoCoPlanetStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SyncData = channel.unary_unary(
                '/coco_planet.CoCoPlanet/SyncData',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=coco__planet__grpc__server__pb2.SyncDataReply.FromString,
                )
        self.SyncControl = channel.unary_unary(
                '/coco_planet.CoCoPlanet/SyncControl',
                request_serializer=coco__planet__grpc__server__pb2.SyncControlRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.SendCommand = channel.unary_unary(
                '/coco_planet.CoCoPlanet/SendCommand',
                request_serializer=coco__planet__grpc__server__pb2.SendCommandRequest.SerializeToString,
                response_deserializer=coco__planet__grpc__server__pb2.SendCommandReply.FromString,
                )


class CoCoPlanetServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SyncData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SyncControl(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendCommand(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CoCoPlanetServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SyncData': grpc.unary_unary_rpc_method_handler(
                    servicer.SyncData,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=coco__planet__grpc__server__pb2.SyncDataReply.SerializeToString,
            ),
            'SyncControl': grpc.unary_unary_rpc_method_handler(
                    servicer.SyncControl,
                    request_deserializer=coco__planet__grpc__server__pb2.SyncControlRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'SendCommand': grpc.unary_unary_rpc_method_handler(
                    servicer.SendCommand,
                    request_deserializer=coco__planet__grpc__server__pb2.SendCommandRequest.FromString,
                    response_serializer=coco__planet__grpc__server__pb2.SendCommandReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'coco_planet.CoCoPlanet', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class CoCoPlanet(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SyncData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/coco_planet.CoCoPlanet/SyncData',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            coco__planet__grpc__server__pb2.SyncDataReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SyncControl(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/coco_planet.CoCoPlanet/SyncControl',
            coco__planet__grpc__server__pb2.SyncControlRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SendCommand(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/coco_planet.CoCoPlanet/SendCommand',
            coco__planet__grpc__server__pb2.SendCommandRequest.SerializeToString,
            coco__planet__grpc__server__pb2.SendCommandReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
