# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: coco_planet_grpc_server.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1d\x63oco_planet_grpc_server.proto\x12\x0b\x63oco_planet\x1a\x1bgoogle/protobuf/empty.proto\"\x1c\n\x0cHelloRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1d\n\nHelloReply\x12\x0f\n\x07message\x18\x01 \x01(\t\"$\n\rSyncDataReply\x12\x13\n\x0bjson_string\x18\x01 \x01(\t\")\n\x12SyncControlRequest\x12\x13\n\x0bjson_string\x18\x01 \x01(\t\")\n\x12SendCommandRequest\x12\x13\n\x0bjson_string\x18\x01 \x01(\t\"\'\n\x10SendCommandReply\x12\x13\n\x0bjson_string\x18\x01 \x01(\t2\xe3\x01\n\nCoCoPlanet\x12>\n\x08SyncData\x12\x16.google.protobuf.Empty\x1a\x1a.coco_planet.SyncDataReply\x12\x46\n\x0bSyncControl\x12\x1f.coco_planet.SyncControlRequest\x1a\x16.google.protobuf.Empty\x12M\n\x0bSendCommand\x12\x1f.coco_planet.SendCommandRequest\x1a\x1d.coco_planet.SendCommandReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'coco_planet_grpc_server_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_HELLOREQUEST']._serialized_start=75
  _globals['_HELLOREQUEST']._serialized_end=103
  _globals['_HELLOREPLY']._serialized_start=105
  _globals['_HELLOREPLY']._serialized_end=134
  _globals['_SYNCDATAREPLY']._serialized_start=136
  _globals['_SYNCDATAREPLY']._serialized_end=172
  _globals['_SYNCCONTROLREQUEST']._serialized_start=174
  _globals['_SYNCCONTROLREQUEST']._serialized_end=215
  _globals['_SENDCOMMANDREQUEST']._serialized_start=217
  _globals['_SENDCOMMANDREQUEST']._serialized_end=258
  _globals['_SENDCOMMANDREPLY']._serialized_start=260
  _globals['_SENDCOMMANDREPLY']._serialized_end=299
  _globals['_COCOPLANET']._serialized_start=302
  _globals['_COCOPLANET']._serialized_end=529
# @@protoc_insertion_point(module_scope)
